name: app_costura
description: App para ajudar você costureira a guardar as medias de suas clientes e realizar orçamento de uma maneira fácil.
version: 0.1.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
