name: app_costura
description: App para ajudar você costureira a guardar as medias de suas clientes e realizar orçamento de uma maneira fácil.
version: 0.1.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  logging: ^1.0.2
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  flutter_modular: ^5.0.2
  flutter_triple: ^1.2.7+2
  flex_color_scheme: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_test: ^1.0.1
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  triple_test: ^1.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/contacts.png
    - assets/images/quote.png
    - assets/images/machine.png
    - assets/images/needle.png
    - assets/images/mannequin.png
    - assets/images/ruler.png
